// PRODUCTION KEYS - Reference global keys set in Netlify
module.exports = {
    GOOGLE_MAPS_API_KEY: GOOGLE_MAPS_API_KEY,
    MAP_BOX_API_KEY: MAP_BOX_API_KEY,
    BRIDGE_INTERACTIVE_API_SERVER_TOKEN: BRIDGE_INTERACTIVE_API_SERVER_TOKEN,
    BRIDGE_INTERACTIVE_API_CLIENT_SECRET: BRIDGE_INTERACTIVE_API_CLIENT_SECRET,
    BRIDGE_INTERACTIVE_API_BROWSER_TOKEN: BRIDGE_INTERACTIVE_API_BROWSER_TOKEN,
    BRIDGE_INTERACTIVE_API_CLIENT_ID: BRIDGE_INTERACTIVE_API_CLIENT_ID,
    MLS_DATASET: MLS_DATASET,
    REDIRECT_DOMAIN: REDIRECT_DOMAIN
};