// PRODUCTION KEYS - Reference global keys set in Netlify
module.exports = {
    GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_API_KEY,
    MAP_BOX_API_KEY: process.env.MAP_BOX_API_KEY,
    BRIDGE_INTERACTIVE_API_SERVER_TOKEN: process.env.BRIDGE_INTERACTIVE_API_SERVER_TOKEN,
    BRIDGE_INTERACTIVE_API_CLIENT_SECRET: process.env.BRIDGE_INTERACTIVE_API_CLIENT_SECRET,
    BRIDGE_INTERACTIVE_API_BROWSER_TOKEN: process.env.BRIDGE_INTERACTIVE_API_BROWSER_TOKEN,
    BRIDGE_INTERACTIVE_API_CLIENT_ID: process.env.BRIDGE_INTERACTIVE_API_CLIENT_ID,
    MLS_DATASET: process.env.MLS_DATASET,
    REDIRECT_DOMAIN: process.env.REDIRECT_DOMAIN
};