// PRODUCTION KEYS - Reference global keys set in Netlify
module.exports = {
    REACT_APP_API_GOOGLE_MAPS_API_KEY: process.env.REACT_APP_API_GOOGLE_MAPS_API_KEY,
    REACT_APP_API_MAP_BOX_API_KEY: process.env.REACT_APP_API_MAP_BOX_API_KEY,
    REACT_APP_API_BRIDGE_INTERACTIVE_API_SERVER_TOKEN: process.env.REACT_APP_API_BRIDGE_INTERACTIVE_API_SERVER_TOKEN,
    REACT_APP_API_BRIDGE_INTERACTIVE_API_CLIENT_SECRET: process.env.REACT_APP_API_BRIDGE_INTERACTIVE_API_CLIENT_SECRET,
    REACT_APP_API_BRIDGE_INTERACTIVE_API_BROWSER_TOKEN: process.env.REACT_APP_API_BRIDGE_INTERACTIVE_API_BROWSER_TOKEN,
    REACT_APP_API_BRIDGE_INTERACTIVE_API_CLIENT_ID: process.env.REACT_APP_API_BRIDGE_INTERACTIVE_API_CLIENT_ID,
    REACT_APP_MLS_DATASET: process.env.REACT_APP_MLS_DATASET,
    REACT_APP_REDIRECT_DOMAIN: process.env.REACT_APP_REDIRECT_DOMAIN
};